### ISSUE TITLE
Unexpected E1029 error

### ISSUE THREAD

**Issue by lingrlongr** [aws-cloudformation/cfn-python-lint#1443]
*cfn-lint version: (0.29.1)*

*Description of issue.*

After this version was released, I started getting an error when linting a template.  This error specific to `BuildSpec` attributes for a `AWS::CodeBuild::Project` project.

    E1029 Found an embedded parameter outside of an "Fn::Sub" at 
    Resources/MyCodeBuild/Properties/Source/BuildSpec
    cloudformation.json:151:11

I mocked up a JSON template that showcases the problem and [attached](https://github.com/aws-cloudformation/cfn-python-lint/files/4383494/cloudformation.txt) it.

**Comment by kddejong** [comment]
it doesn't seem to like `${BUCKET}` inside that string.  Which is a thing we are looking for. 

I'm not sure how it wasn't found previously.  Trying to investigate that quickly.

Additionally we have a way to make exceptions.  Build Spec looks like a good use case for an exception since you can be putting in some scripting in there.

**Comment by kddejong** [comment]
Just an update here.  #1430 is the PR with the change.  The old regex would cause hanging on a large strings.  For some reason the old regex while very greedy seem to not go much past new lines.  I'm a little bit confused there.  I put in an exception for the BuildSpec.

**Comment by lingrlongr** [comment]
Awesome!  Thanks for the quick turnaround!  I'll look forward to the next release and will just pin with `cfn-lint!=0.29.1` in the meantime.
