### ISSUE TITLE
Allow for specific variables to remain unused

### ISSUE THREAD

**Issue by RobCoops** [aws-cloudformation/cfn-python-lint#1626]
**cfn-lint version:** _latest_

**Description of issue.**
For reasons beyond my comprehension our CI/CD process reads the contents of the cloudformation template and uses variables set in the template to associate templates with services, teams, etc.

In quite a few templates these variables are unused for anything else, which triggers the linter (rightfully so) complaining about an unused variable. Of course we could suppress the rule checking for unused variables but that is kind of silly as there are many other variables that should be used or if they are unused removed from the template.

Would it be possible to allow one to not just switch rules on or off but to tell them to ignore certain situations. If rule encounters something that looks exactly like this: `some json object` treat is as if its good.

I know this is an edge case and I can imagine there is no need to do this, on the other hand I do also see situations in which one might encounter an issue with the linter not wanting to stop it or skip rules that outside of this one case work perfectly fine.

**Comment by PatMyron** [comment]
There are [inline ignores at the resource-level using Metadata](https://github.com/aws-cloudformation/cfn-python-lint#resource-based-metadata). Since the other [template sections](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html) don't support Metadata, I think I'm going to merge this into https://github.com/aws-cloudformation/cfn-python-lint/issues/113
