### ISSUE TITLE
 Invalid Property Resources: Throughput

### ISSUE THREAD

**Issue by chenwany** [aws-cloudformation/cfn-python-lint#1837]
*cfn-lint version: (`0.44.0`)*

*Description of issue.*
Hi,
Recently EBS introduced the gp3 volume type. This volume type enables customers to configure IOPS and throughput independently, there is also corresponding CFN resource Throughput parameter.

When will lint become able to validate `Throughput`?

**Comment by PatMyron** [comment]
Could you provide a sample template? Or specify which resource type this property type was recently added to?

This likely involves https://github.com/aws-cloudformation/cfn-python-lint/issues/1219 since no [Resource Specfications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) have been released for weeks

**Comment by chenwany** [comment]
Thanks for your reply!
It is AWS::EC2::Volume, property `Throughput`, it is a new parameter haven't be in the document. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html

**Comment by chenwany** [comment]
Hi, this resource `Throughput` is already in [Resource Specfications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html), but the Cfn linters check still fail with Invalid Property Resources: Throughput

**Comment by PatMyron** [comment]
[just merged in yesterday](https://github.com/aws-cloudformation/cfn-python-lint/pull/1831), will be fixed in the next release
