### ISSUE TITLE
Optional AWS::Serverless Transform

### ISSUE THREAD

**Issue by gitFurious** [aws-cloudformation/cfn-python-lint#1866]
I'm interested in writing some internal linting rules, specific to our organisation, against _AWS::Serverless_ resources _pre-transformation_.

I don't think that's possible at the moment but would something like an optional flag to skip the SAM transformation be feasible?

Would a PR for this be welcomed?

Cheers.

**Comment by kddejong** [comment]
Thinking about the parameter idea.  The simple answer is that should be workable however I would want to test a few things but I think this shouldn't result in any downstream issues. 

The other option would be here is to use the [integration](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/getting_started/integration.md) approach. With this approach you have a little more control on how things get called and what template gets passed to it.  This may not be as scalable if you want to distribute this version to internal customers but may work if you are looking to use it in a pipeline.

**Comment by PatMyron** [comment]
Something to consider is if that optional flag should be per-run or just per-rule. I think running [all rules](https://github.com/aws-cloudformation/cfn-python-lint/blob/master/docs/rules.md) pre-transformation could cause problems since the expectation has always been that they'll run post-transformation while rules were written. Running only specific rules pre-transformation might lead to fewer issues

**Comment by gitFurious** [comment]
Cheers for the response @kddejong and @PatMyron, I hadn't considered the integration approach but it looks like a good start and will most likely work for my use case.

I'll go with that approach for now 👍 

Cheers.
