### ISSUE TITLE
Incorrect DMS Endpoint EngineName validation for DocumentDB

### ISSUE THREAD

**Issue by fuszumasa** [aws-cloudformation/cfn-python-lint#1916]
According to CloudFormation documentation, the correct value for DMS DocumentDB Endpoint EngineName parameter is "docdb" (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-enginename). Linter lists "documentdb" as a supposedly correct one. Using a suggested "documentdb" results in failure in processing the template.

**Comment by PatMyron** [comment]
[docs have changed](https://web.archive.org/web/20200502024828if_/https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-enginename) since https://github.com/aws-cloudformation/cfn-python-lint/pull/1473
https://github.com/aws-cloudformation/cfn-python-lint/blob/df9b21419ac303be2d50bb3afdaf3fd72da58bc7/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json#L137-L159
