### ISSUE TITLE
E3008 Property "ServiceRole" has no valid Refs to Resources at Resources/CodeBuildProject/Properties/ServiceRole/Ref

### ISSUE THREAD

**Issue by gergnz** [aws-cloudformation/cfn-python-lint#813]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.18.1

*Description of issue.*

Using the default example template for CodeBuild (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html)

Get the following:
```
E3008 Property "ServiceRole" has no valid Refs to Resources at Resources/CodeBuildProject/Properties/ServiceRole/Ref
x.yaml:6:7
```

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html

  * If present, please add links to the (official) documentation for clarification.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html

  * Validate if the issue still exists with the latest version of `cfn-lint` and/or the latest Spec files

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

Confirmed. Still exists.

**Comment by ramtruck3** [comment]
I do like doing this

**Comment by ramtruck3** [comment]
But I need to go find some money around where I can get the money I minded for early its everywhere it's been taking from 3 time and I need to try and get for my kids.

**Comment by ramtruck3** [comment]
I will be back

**Comment by kddejong** [comment]
@gergnz This one is tricky.  I'm going to get @cmmeyer position on this too.  So here is what I have found.
A line per test I ran.
- ServiceRole can Ref a Role when the Path is `/`
- ServiceRole can GetAtt a Role when the Path is `/`
- ServiceRole can NOT Ref a Role when the Path is `/test/`
- ServiceRole can GetAtt a Role when the Path is `/test/`

I don't like that this currently gives an error as our goal is to only show errors when it will error.  However in this case the Ref is fairly conditional based on what the value of the Path is and if its set. We have been trying to build these relationships in the spec so that they aren't based on values inside the Ref-ed resource.  I like pushing for GetAtt as it will always work.  

@cmmeyer we could accept both the Ref/GetAtt portion of the spec and then write an additional rule to look for these Path scenarios.  This isn't the only resource we have seen this one.  It seems like some resource APIs will search for the role name and get it no matter what the path is and some try to build the ARN assuming there is no path (based on my really basic observations)

**Comment by gergnz** [comment]
Interesting. I didn't pick up on the fact that Ref doesn't return the Arn, but returns the name of the Role. So Technically GetAtt is correct and Ref is incorrect.

It's interesting that some examples on the referenced cloudformation documentation page use Ref and some use GetAtt.

I've raised a PR to update the documentation examples: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/307
